# ビルドステージ
FROM golang:1.25.4 AS builder

WORKDIR /app
COPY . .
RUN go build -tags lambda.norpc -o main ./handler/main.go

# 本番ステージ
FROM public.ecr.aws/lambda/provided:al2023
COPY --from=builder /app/main ./main
ENTRYPOINT [ "./main" ]